image: migamake/haskell-build:8.6.5

stages:
  - build
  - test
  - release

variables:
  PACKAGE_NAME: homplexity
  EXEC_NAME:    homplexity-cli

cache:
  paths:
    - .cabal-sandbox

.build_exe:
  image: migamake/haskell-build:$GHC_VER
  stage: build
  script:
    - cabal install hspec-discover # til it is included in build image
    - cabal sandbox init
    - cabal --version
    - ghc   --version
    - cabal update
    - "sed --in-place 's/-- STATIC: //' $PACKAGE_NAME.cabal"
    - cabal install --verbose --dependencies-only --enable-tests
    - cabal configure --enable-tests
    - cabal test
    - mkdir -p bin sdist
    - cabal install --bindir=bin/
    - cabal sdist   --builddir=sdist/
    - cabal haddock --builddir hackage-docs --for-hackage
    - bin/homplexity-cli lib/

build_8_6_5:
  variables:
    GHC_VER: 8.6.5
  extends: .build_exe
  artifacts:
    paths:
      - sdist/$PACKAGE_NAME-*[0-9].tar.gz
      - hackage-docs/$PACKAGE_NAME-*-docs.tar.gz
      - bin/homplexity-cli
    expire_in: 2 weeks

build_8_4_4:
  variables:
    GHC_VER: 8.4.4
  extends: .build_exe

build_8_2_2:
  variables:
    GHC_VER: 8.2.2
  extends: .build_exe

build_8_0_2:
  variables:
    GHC_VER: 8.0.2
  extends: .build_exe
  retry: 2
  allow_failure: true

build_8_10_1:
  variables:
    GHC_VER: 8.10.1
  extends: .build_exe
  retry: 2
  allow_failure: true

build_8_8_2:
  variables:
    GHC_VER: 8.8.2
  extends: .build_exe
  retry: 2
  allow_failure: true

build_7_10_3:
  variables:
    GHC_VER: 7.10.3
  extends: .build_exe

build_7_8_4:
  variables:
    GHC_VER: 7.8.4
  extends: .build_exe

test_distribution:
  stage: test
  script:
    - cabal update
    - mkdir -p bin
    - cabal install sdist/$PACKAGE_NAME*[0-9].tar.gz --bindir=bin/
    - tar xzf sdist/$PACKAGE_NAME*[0-9].tar.gz
    - bin/homplexity-cli homplexity-*/lib
  dependencies:
    - build_8_6_5
  artifacts:
    paths:
      - bin/homplexity-cli

release_to_hackage:
  stage: release
  script:
    - cabal upload --username="$HACKAGE_USER" --password="$HACKAGE_PASSWORD" sdist/$PACKAGE_NAME-*[0-9].tar.gz
    - cabal upload --username="$HACKAGE_USER" --password="$HACKAGE_PASSWORD" -d hackage-docs/$PACKAGE_NAME-*-docs.tar.gz
  dependencies:
    - build_8_6_5
  when: manual
  only:
    - master
