image: migamake/haskell-build:8.6.2

stages:
  - build
  - test

cache:
  paths:
    - .cabal-sandbox

.build_exe:
  image: migamake/haskell-build:$GHC_VER
  stage: build
  script:
    - cabal sandbox init
    - cabal --version
    - ghc   --version
    - cabal update
    - "sed --in-place 's/-- STATIC: //' homplexity.cabal"
    - cabal install --verbose --only-dependencies
    - cabal test
    - mkdir -p bin sdist
    - cabal install --bindir=bin/
    - bin/homplexity-cli Language/
  artifacts:
    paths:
      - bin/homplexity-cli

build_8_6_2:
  variables:
    GHC_VER: 8.6.2
  extends: .build_exe

build_8_4_4:
  variables:
    GHC_VER: 8.4.4
  extends: .build_exe

source_dist:
  image: migamake/haskell-build:${GHC_VER}
  stage: build
  script:
    - cabal --version
    - ghc   --version
    - cabal sdist --output=sdist/
  artifacts:
    paths:
      - sdist/
    expire_in: 1 week

test_distribution:
  stage: test
  script:
    - cabal update
    - mkdir -p bin
    - cabal install sdist/* --bindir=bin/
    - tar xzf sdist/*
    - bin/homplexity-cli homplexity-*/Language
  dependencies:
    - source_dist
