image: migamake/haskell-build:8.6

stages:
  - docker
  - build
  - test
  - release

variables:
  PACKAGE_NAME:       homplexity
  EXEC_NAME:          homplexity-cli
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.1-dind

cache:
  paths:
    - .cabal-sandbox
    - /root/.cabal

# Build for images up to 8.6, with `cabal-install` 2.x

.build_exe:
  image: migamake/haskell-build:$GHC_VER
  stage: build
  script:
    - cabal --version
    - ghc   --version
    - cabal update
    - cabal install --dependencies-only --enable-tests
    - "echo sed --in-place 's/-- STATIC: //' $PACKAGE_NAME.cabal" # disabled for latest Ubuntu
    - cabal v1-configure --enable-tests --allow-newer
    - cabal v1-build
    - cabal v1-test
    - mkdir -p bin sdist
    - cabal install --bindir=bin/
    - cabal sdist   --builddir=sdist/
    - cabal haddock --builddir hackage-docs --for-hackage
    - bin/homplexity-cli lib/

# Build for images 8.8 and above with `cabal-install` v3.x

.new_build_exe:
  image: migamake/haskell-build:$GHC_VER
  stage: build
  script:
    - cabal --version
    - ghc   --version
    - cabal update
    - cabal build --enable-tests --allow-newer
    - cabal test --allow-newer
    - mkdir -p bin sdist
    - cabal install --bindir=bin/ --allow-newer
    - cabal sdist   --builddir=sdist/ --allow-newer
    - cabal haddock --builddir hackage-docs --haddock-for-hackage --allow-newer
    - cabal exec -- homplexity-cli lib/ # path is dist/build/homplexity-cli

build_8_6:
  variables:
    GHC_VER: "8.6"
  extends: .build_exe
  artifacts:
    paths:
      - sdist/$PACKAGE_NAME-*[0-9].tar.gz
      - hackage-docs/$PACKAGE_NAME-*-docs.tar.gz
      - bin/homplexity-cli
    expire_in: 2 weeks

build_8_4:
  variables:
    GHC_VER: "8.4"
  extends: .build_exe

build_8_10:
  variables:
    GHC_VER: "8.10"
  extends: .new_build_exe
  retry: 2
  allow_failure: true

build_8_8:
  variables:
    GHC_VER: "8.8"
  extends: .new_build_exe
  retry: 2
  allow_failure: true

test_distribution:
  stage: test
  script:
    - cabal update
    - mkdir -p bin
    - cabal install sdist/$PACKAGE_NAME*[0-9].tar.gz --bindir=bin/
    - tar xzf sdist/$PACKAGE_NAME*[0-9].tar.gz
    - bin/homplexity-cli homplexity-*/lib
  dependencies:
    - build_8_6
  artifacts:
    paths:
      - bin/homplexity-cli

docker_build:
  image: docker
  stage: docker
  script:
    - mkdir -p workdir
    - docker build . -t migamake/homplexity -f Dockerfile
    - docker run migamake/homplexity -v $PWD:/workdir /workdir
    - docker save --output homplexity.docker migamake/homplexity:latest
    - ls -alth homplexity.docker
  artifacts:
    paths:
      - homplexity.docker

release_to_hackage:
  stage: release
  script:
    - cabal upload --username="$HACKAGE_USER" --password="$HACKAGE_PASSWORD" sdist/$PACKAGE_NAME-*[0-9].tar.gz
    - cabal upload --username="$HACKAGE_USER" --password="$HACKAGE_PASSWORD" -d hackage-docs/$PACKAGE_NAME-*-docs.tar.gz
  dependencies:
    - build_8_6
  when: manual
  only:
    - master

release_to_dockerhub:
  image: docker
  stage: release
  script:
    - docker load homplexity.docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    - docker push migamake/homplexity;
  dependencies:
    - docker_build
  when: manual
  only:
    - master

