image: migamake/haskell-build:8.6.2

stages:
  - build
  - test

cache:
  paths:
    - .cabal-sandbox

install_exe:
  stage: build
  script:
    - cabal sandbox init
    - cabal --version
    - ghc   --version
    - cabal update
    - "sed --in-place 's/-- STATIC: //' homplexity.cabal"
    - cabal install --verbose --only-dependencies
    - mkdir -p bin
    - cabal test
    - cabal install --bindir=bin/
  artifacts:
    paths:
      - bin/homplexity-cli

executable_test:
  stage: test
  script:
    - pwd
    - ls
    - ls bin/
    - bin/homplexity-cli Language/
  dependencies:
    - install_exe
