image: migamake/haskell-build:8.6

stages:
  - build
  - test
  - release

variables:
  PACKAGE_NAME: homplexity
  EXEC_NAME:    homplexity-cli

cache:
  paths:
    - .cabal-sandbox

# Build for images up to 8.6, with `cabal-install` 2.x

.build_exe:
  image: migamake/haskell-build:$GHC_VER
  stage: build
  script:
    - cabal --version
    - ghc   --version
    - cabal update
    - cabal install --dependencies-only --enable-tests
    - "echo sed --in-place 's/-- STATIC: //' $PACKAGE_NAME.cabal" # disabled for latest Ubuntu
    - cabal v1-configure --enable-tests --allow-newer
    - cabal v1-build
    - cabal v1-test
    - mkdir -p bin sdist
    - cabal install --bindir=bin/
    - cabal sdist   --builddir=sdist/
    - cabal haddock --builddir hackage-docs --for-hackage
    - bin/homplexity-cli lib/

# Build for images 8.8 and above with `cabal-install` v3.x

.new_build_exe:
  image: migamake/haskell-build:$GHC_VER
  stage: build
  script:
    - cabal --version
    - ghc   --version
    - cabal update
    - cabal build --enable-tests --allow-newer
    - cabal test
    - mkdir -p bin sdist
    - cabal install --bindir=bin/
    - cabal sdist   --builddir=sdist/
    - cabal haddock --builddir hackage-docs --haddock-for-hackage
    - cabal exec -- homplexity-cli lib/ # path is dist/build/homplexity-cli

build_8_6:
  variables:
    GHC_VER: "8.6"
  extends: .build_exe
  artifacts:
    paths:
      - sdist/$PACKAGE_NAME-*[0-9].tar.gz
      - hackage-docs/$PACKAGE_NAME-*-docs.tar.gz
      - bin/homplexity-cli
    expire_in: 2 weeks

build_8_4:
  variables:
    GHC_VER: "8.4"
  extends: .build_exe

build_8_10:
  variables:
    GHC_VER: "8.10"
  extends: .new_build_exe
  retry: 2
  allow_failure: true

build_8_8:
  variables:
    GHC_VER: "8.8"
  extends: .new_build_exe
  retry: 2
  allow_failure: true

test_distribution:
  stage: test
  script:
    - cabal update
    - mkdir -p bin
    - cabal install sdist/$PACKAGE_NAME*[0-9].tar.gz --bindir=bin/
    - tar xzf sdist/$PACKAGE_NAME*[0-9].tar.gz
    - bin/homplexity-cli homplexity-*/lib
  dependencies:
    - build_8_6
  artifacts:
    paths:
      - bin/homplexity-cli

docker_build:
  stage: test
  script:
    - docker build . -t homplexity-image -f Dockerfile
    - docker run homplexity-image -v $PWD:/build /build/

release_to_hackage:
  stage: release
  script:
    - cabal upload --username="$HACKAGE_USER" --password="$HACKAGE_PASSWORD" sdist/$PACKAGE_NAME-*[0-9].tar.gz
    - cabal upload --username="$HACKAGE_USER" --password="$HACKAGE_PASSWORD" -d hackage-docs/$PACKAGE_NAME-*-docs.tar.gz
  dependencies:
    - build_8_6
  when: manual
  only:
    - master

